on:
  push:
    branches:
      - '**'

jobs:
  freebsd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true
      - name: Customize disk image
        shell: bash
        run: |
          whoami
          find /lib/modules/$(uname -r) -type f -name '*.ko*'
          cat /boot/config-$(uname -r)
          exit 0

          apt update
          apt install -y libguestfs-tools curl xz

          curl -LO https://download.freebsd.org/releases/VM-IMAGES/13.2-RELEASE/amd64/Latest/FreeBSD-13.2-RELEASE-amd64.vhd.xz
          xz -d -T0 --verbose FreeBSD-13.2-RELEASE-amd64.vhd.xz

          cat <<EOF | guestfish -a FreeBSD-13.2-RELEASE-amd64.vhd
          run
          list-filesystems
          mount-vfs ufstype=ufs2 ufs /dev/sda4 /
          copy-in files/loader.conf /boot/
          write-append /etc/rc.conf 'sshd_enable="YES"'

          EOF
